--- #YAML:1.0
name:               MARC-Utils-MARC2Pairs
version:            0.02
abstract:           Perl module that provides routines to
author:
    - Brad Baxter <bbaxter@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Pairs:   0
    MARC::Record:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
